### ISSUE TITLE
Occasional `Cannot read property 'fingerprint' of null`

### ISSUE THREAD

**Issue by meeDamian** [lamassu/lamassu-machine#10]
When running `node bin/lamassu-machine` (with `--mock-btc`, `--mock-bv`, and `--mock-pair`) this error occasionally shows up:

```
LOG TypeError: Cannot read property 'fingerprint' of null
    at /home/mee/dev/forks/lamassu/lamassu-machine/lib/trader.js:69:56
    at IncomingMessage.<anonymous> (/home/mee/dev/forks/lamassu/lamassu-machine/node_modules/jsonquest/lib/jsonquest.js:83:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)
```

Seems like `res.socket.getPeerCertificate()` method sometimes returns `null`.

**Comment by naconner** [comment]
Due to version local node version. Should be 0.10.18.

Method to downgrade: http://codebyte.in/upgrade-downgrade-nodejs-nvm/
