### ISSUE TITLE
QuadrigaCX Ticker and API Trading

### ISSUE THREAD

**Issue by daldwinc** [lamassu/lamassu-machine#105]
QuadrigaCX (https://www.quadrigacx.com/) is a popular Canadian exchange, with a high volume for CAD trading pairs.

This enhancement request is two part:

1. Implement the option of using the QuadrigaCX ticker as spot price source

2. Implement auto-rebuy functionality for QuadrigaCX

Their API documentation can be found here: https://www.quadrigacx.com/api_info

Cheers,
Dave

**Comment by naconner** [comment]
Thanks, Dave. This is actually relevant on https://github.com/lamassu/lamassu-server as that handles the trading, rather than machine. Could you file there?
