### ISSUE TITLE
Complete transaction when network connectivity returns

### ISSUE THREAD

**Issue by joshmh** [lamassu/lamassu-machine#13]
Currently, if network connectivity goes down during a transaction, the transaction will fail and the machine will return the the Start screen upon network reconnect.
# Revised polling
1. Poll more frequently, let's say once a second.
2. Only trigger _network down_ screen if: (a) no successful poll in last 120s; (b) successful poll but price feed is down and price is stale (say, 5m old); (c) wallet balance is stale (5m).
3. Trigger _network up_ on first successful poll or update.
# Revised transaction processing
1. If **sendTransaction** fails, keep a local record of the last transaction.
2. Continue sending **sendTransaction** request once a second for 120 seconds until machine receives a response from server.
3. After 120s, show informative network down screen, but keep trying **sendTransaction** indefinitely.
4. In **lamassu-server**, if BTM hasn't polled for 120 seconds, send the partial transaction to the user.
5. If a bill was inserted after the network went down, the amount in **sendTransaction** will be higher than the amount the server has sent. Server should send the remaining coins to the end user.

**Note**: Once the transaction has begun and bills have been inserted, machine should not go into _network down_ screen at all. We will just do our best to send the transaction.
# UI changes
- Sorry/Down screen should explain that the transaction will be sent momentarily.
- If BTM was unable to report the last bill, inform user that the last bill will be sent later.
- When network returns, a brief screen should indicate that the transaction was sent successfully. This may only be useful if the network downtime was brief.

**Comment by naconner** [comment]
Now included in production and v3 beta. Closing.
