### ISSUE TITLE
Cannot read property 'hasCert' of undefined >     at Brain.run

### ISSUE THREAD

**Issue by H4dro** [lamassu/lamassu-machine#131]
Hi, 
I'm getting the following error when trying to on a Mac 10.12.6 following the instructions here https://github.com/lamassu/lamassu-machine

I have tried various versions of node but still cannot resolve this error?

npm -v 5.6.0
node -v v8.11.3

> node bin/lamassu-machine --mockTrader --mockCam --mockBillDispenser --mockBv /dev/ttys004
> 2018-08-10T16:15:05.521Z LOG Lamassu Cryptomat software initialized.
> 2018-08-10T16:15:05.530Z LOG version: 2.0.6, cpuLoad: 3.05, memUse: 48.1 MB, memFree: 9.5%
>   nodeUptime: 0.00h, osUptime: 210.15h
> 2018-08-10T16:15:05.531Z LOG lamassu-machine bailing out momentarily...
> 2018-08-10T16:15:05.532Z LOG TypeError: Cannot read property 'hasCert' of undefined
>     at Brain.run (/Users/hydro/lamassu-machine/lib/brain.js:148:21)
>     at startBrain (/Users/hydro/lamassu-machine/bin/lamassu-machine:34:9)
>     at Object.<anonymous> (/Users/hydro/lamassu-machine/bin/lamassu-machine:40:1)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:191:16)
> 2018-08-10T16:15:05.532Z LOG TypeError: Cannot read property 'hasCert' of undefined
>     at Brain.run (/Users/hydro/lamassu-machine/lib/brain.js:148:21)
>     at startBrain (/Users/hydro/lamassu-machine/bin/lamassu-machine:34:9)
>     at Object.<anonymous> (/Users/hydro/lamassu-machine/bin/lamassu-machine:40:1)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:191:16)
> 2018-08-10T16:15:07.969Z LOG connected to browser
> 2018-08-10T16:15:12.533Z LOG lamassu-machine bailing out
> 2018-08-10T16:15:12.533Z LOG lamassu-machine exiting

Thanks

**Comment by naconner** [comment]
Hi @H4dro. From that output, I see an old version was checked out:
```
2018-08-10T16:15:05.530Z LOG version: 2.0.6, cpuLoad: 3.05, memUse: 48.1 MB, memFree: 9.5%
nodeUptime: 0.00h, osUptime: 210.15h
```
The latest production release is v3.6.5. Instructions can be found here:

https://github.com/lamassu/lamassu-machine/wiki/Running-v3-locally-on-Debian-or-Ubuntu

Hope that helps.

Please note that we do not currently offer support for running the software on an environment outside of our machines. Please feel free to contact us if we can help otherwise: https://lamassu.is/contact/
