### ISSUE TITLE
More detailed Sorry screen (at least in the logs... or somewhere)

### ISSUE THREAD

**Issue by keo** [lamassu/lamassu-machine#17]
The Sorry... screen can come up for a multitude of reasons. It would be great to get some more information on what happened. It would help a lot with troubleshooting.

Either through a secret tap combination (maybe nonsensitive info could be shared on the screen, after tapping a small details icon)

At the place we're operating it waiters are helping with simpler problems. They could troubleshoot the Sorry... screen themselves and help customers if they would get more info.

**Comment by naconner** [comment]
This is handled well in v3, which provides machine log uploads to the admin, SMS/email notifications on machine events, and server status in the admin.
