### ISSUE TITLE
Operator access to machine logs

### ISSUE THREAD

**Issue by keo** [lamassu/lamassu-machine#18]
We've gone through a multitude of problems before launching the ATM.

It would have helped a lot if we could have SSH access to the Nexus7, or at least be able to pull logs somehow.

**Comment by debreczeni** [comment]
@naconner How should we go about this? Any news on this?

**Comment by naconner** [comment]
@debreczeni Glad it's sorted. I understand you have remote telnet access by which to access the logs.

Would be good to have this as a global capability. As development bandwidth allows, we'll look to do so.

**Comment by marian001** [comment]
@debreczeni could you please describe how you're connecting to your machine and/or how to set up such connection?

**Comment by naconner** [comment]
Remote machine log retrieval merged in v3 with https://github.com/lamassu/lamassu-machine/commit/ec23760124639633ba462c1f8cd502135e3c1af0 and https://github.com/lamassu/lamassu-machine/commit/68ceaea04b65d601a61726d02286353dfba8e684.
