### ISSUE TITLE
Wi-Fi connectivity lost, is not regained - requires reboot and reconnect in Trofa

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-machine#28]
So far, only Trofas have been reported to have this issue. At some point, internet connectivity is lost (with no further indication in node logs than `networkDown`), and is never regained until the machine is rebooted and reconnected to Wi-Fi.

In resolving this, I have so far only recommended power pulls, since this is easily done without needing an external key. Therefore, I am unsure if this persists through a Nexus power reboot.

Is there a way we can have the machine release/renew the IP periodically?

**Comment by naconner** [comment]
@joshmh Candidate for 0.5.0 milestone.

**Comment by joshmh** [comment]
Are you able to replicate this, say by resetting the router DHCP table?

**Comment by naconner** [comment]
No longer reported in later versions. Closing.
