### ISSUE TITLE
Missing font: Brandon Text

### ISSUE THREAD

**Issue by imrehg** [lamassu/lamassu-machine#4]
When opening the main interface, I get a bunch of errors in the inspector about the missing Brandon Text font. It seems like now switched to Surface Pro, but Brandon Text is still being tried to be pulled in by `ui/css/font.css`.

```
Failed to load resource: net::ERR_FILE_NOT_FOUND file://<somewhere>/lamassu-machine/ui/css/fonts/brandon_txt_reg-webfont.woff
Failed to load resource: net::ERR_FILE_NOT_FOUND file://<somewhere>/lamassu-machine/ui/css/fonts/brandon_txt_blk-webfont.woff
Failed to load resource: net::ERR_FILE_NOT_FOUND file://<somewhere>/lamassu-machine/ui/css/fonts/brandon_txt_bld-webfont.woff
Failed to load resource: net::ERR_FILE_NOT_FOUND file://<somewhere>/lamassu-machine/ui/css/fonts/brandon_txt_light-webfont.woff
```

Would be good to either add this font too, or remove the references to it for clarity.

**Comment by naconner** [comment]
This hasn't been an issue on any of my recent Debian and Ubuntu installs. Closing unless still relevant.
