### ISSUE TITLE
README.md does not mention libBarcodeScanner.* libraries

### ISSUE THREAD

**Issue by haxwell** [lamassu/lamassu-machine#40]
I think the README.md should mention the Manatee libBarcodeScanner libraries, and perhaps give a bit of insight on how/where to install them.

I downloaded the demo app from Manatee, and copied _libBarcodeScanner.so_ and _libBarcodeScanner.a_ to /usr/local/lib.

Is that a recommended way of installing these libs?

If they are not in place, the _npm install_ process fails, and at least the Manatee nodejs dependency is not in place.

**Comment by drkyro** [comment]
Can the readme file be looked at, its impossible to get this running locally right now.

**Comment by naconner** [comment]
Old issue, closing. Instructions for running current v3 beta:

https://github.com/lamassu/lamassu-machine/wiki/Running-v3-locally-on-Debian-or-Ubuntu
https://support.lamassu.is/hc/en-us/articles/115001203791-Setting-up-the-Admin-Beta-
