### ISSUE TITLE
How do you use mock?

### ISSUE THREAD

**Issue by grintor** [lamassu/lamassu-machine#45]
Where do I put this jpg of a qr code to have it used in the mock camera? I have tried editing device-config.json and pointing mockQR to it. I have even tried replacing the compliance license.jpg thinking it was pointed to that by default (from looking at lib/configuration.js)

**Comment by joshmh** [comment]
The mock camera doesn't currently read qr code images, it just feeds lamassu-machine a Bitcoin address from the command line as if it was scanned in via the camera.
