### ISSUE TITLE
ATM wants to connect to wifi despite it has wired access

### ISSUE THREAD

**Issue by keo** [lamassu/lamassu-machine#48]
Hi,

When booting up, checkWifiStatus only checks for a wired connection once, then goes to the wifi selection screen.

The eth0 interface comes up a few seconds later, but the machine is already stuck at the wifi screen.

The connection should be checked periodically on the wifi screen as well and continue booting as soon as eth0 comes up.

Entering the wifi password isn't an option because then wlan0 becomes the default interface and the connection gets very sloppy.

The workaround I did now is I created a script that waits 15 seconds then does a `killall node`. It is run once from inittab upon boot. When the brain restarts, it correctly detects the wired connection and then procceeds to Booting up... then functions as normal. This is not optimal of course and a patch would be great. I tried patching it here but I couldn't get it to work properly to still show the wifi screen while re-scanning.

(hw: N7G1)

**Comment by naconner** [comment]
Resolved in late 0.4.x or early 0.5.x versions by continually checking for presence of Ethernet while on the select Wi-Fi screen.
