### ISSUE TITLE
Cannot open '/dev/video0': 16, Device or resource busy

### ISSUE THREAD

**Issue by joshmh** [lamassu/lamassu-machine#49]
Apparently camera occasionally not shutting down correctly:
https://gist.github.com/anonymous/9aff11cee3f626ca462b

See this Gist for DEBUG legend:

https://gist.github.com/joshmh/b768a29304220488a62e

**Comment by naconner** [comment]
Old, closing. Can turn back to camera behaviour with a focus on v3 if still an issue.
