### ISSUE TITLE
disregard

### ISSUE THREAD

**Issue by jamesdwilson** [lamassu/lamassu-machine#50]

**Comment by joshmh** [comment]
Hi @jamesdwilson,

Which OS are you using? We haven't tested with node 0.11, just 0.10. Did you follow the instructions from here?

https://github.com/lamassu/node-manatee/blob/master/README.md

**Comment by jamesdwilson** [comment]
Thanks, now I am here:

$ sudo mv libBarcodeScanner.*  /usr/local/lib
[sudo] password for james: 
james@agape ~ $ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.11.10 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/james/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/james/.node-gyp/0.11.10/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/james/.node-gyp/0.11.10',
gyp info spawn args   '-Dmodule_root_dir=/home/james',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home/james) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:104:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:862:12)
gyp ERR! System Linux 3.8.0-35-generic
gyp ERR! command "node" "/usr/bin/node-gyp" "configure"
gyp ERR! cwd /home/james
gyp ERR! node -v v0.11.10
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
james@agape ~ $ cd projects/
james@agape ~/projects $ git clone git@github.com:lamassu/node-manatee.git
Cloning into 'node-manatee'...
remote: Counting objects: 62, done.
remote: Total 62 (delta 0), reused 0 (delta 0), pack-reused 62
Receiving objects: 100% (62/62), 23.72 KiB, done.
Resolving deltas: 100% (21/21), done.
james@agape ~/projects $ cd node-manatee/
james@agape ~/projects/node-manatee $ node-gyp configuregyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.11.10 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/james/projects/node-manatee/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/james/.node-gyp/0.11.10/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/james/.node-gyp/0.11.10',
gyp info spawn args   '-Dmodule_root_dir=/home/james/projects/node-manatee',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
james@agape ~/projects/node-manatee $ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.11.10 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/james/projects/node-manatee/build'
  CXX(target) Release/obj.target/manatee/src/manatee.o
../src/manatee.cc:15:26: error: ‘Arguments’ does not name a type
../src/manatee.cc:15:37: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
In file included from /home/james/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../src/manatee.cc:1:
/home/james/.node-gyp/0.11.10/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> Scan(const int&)’:
/home/james/.node-gyp/0.11.10/deps/v8/include/v8.h:768:13: error: ‘v8::HandleScope::HandleScope()’ is private
../src/manatee.cc:16:15: error: within this context
../src/manatee.cc:18:12: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
../src/manatee.cc:24:35: error: invalid types ‘const int[int]’ for array subscript
../src/manatee.cc:27:25: error: invalid types ‘const int[int]’ for array subscript
../src/manatee.cc:28:25: error: invalid types ‘const int[int]’ for array subscript
../src/manatee.cc:29:29: error: invalid types ‘const int[int]’ for array subscript
../src/manatee.cc:30:29: error: invalid types ‘const int[int]’ for array subscript
../src/manatee.cc:60:10: error: expected primary-expression before ‘*’ token
../src/manatee.cc:60:11: error: ‘slowBuffer’ was not declared in this scope
../src/manatee.cc: At global scope:
../src/manatee.cc:71:30: error: ‘Arguments’ does not name a type
../src/manatee.cc:71:41: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
In file included from /home/james/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../src/manatee.cc:1:
/home/james/.node-gyp/0.11.10/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> Register(const int&)’:
/home/james/.node-gyp/0.11.10/deps/v8/include/v8.h:768:13: error: ‘v8::HandleScope::HandleScope()’ is private
../src/manatee.cc:72:15: error: within this context
../src/manatee.cc:74:12: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
../src/manatee.cc:80:29: error: invalid types ‘const int[int]’ for array subscript
../src/manatee.cc:81:37: error: invalid types ‘const int[int]’ for array subscript
../src/manatee.cc:82:32: error: invalid types ‘const int[int]’ for array subscript
../src/manatee.cc: At global scope:
../src/manatee.cc:88:29: error: ‘Arguments’ does not name a type
../src/manatee.cc:88:40: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
In file included from /home/james/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../src/manatee.cc:1:
/home/james/.node-gyp/0.11.10/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> Version(const int&)’:
/home/james/.node-gyp/0.11.10/deps/v8/include/v8.h:768:13: error: ‘v8::HandleScope::HandleScope()’ is private
../src/manatee.cc:89:15: error: within this context
../src/manatee.cc: In function ‘void RegisterModule(v8::Handle<v8::Object>)’:
../src/manatee.cc:102:31: error: invalid conversion from ‘v8::Handle<v8::Value> (*)(const int&)’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
In file included from /home/james/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../src/manatee.cc:1:
/home/james/.node-gyp/0.11.10/deps/v8/include/v8.h:3346:34: error:   initializing argument 1 of ‘static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)’ [-fpermissive]
../src/manatee.cc:104:35: error: invalid conversion from ‘v8::Handle<v8::Value> (*)(const int&)’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
In file included from /home/james/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../src/manatee.cc:1:
/home/james/.node-gyp/0.11.10/deps/v8/include/v8.h:3346:34: error:   initializing argument 1 of ‘static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)’ [-fpermissive]
../src/manatee.cc:106:34: error: invalid conversion from ‘v8::Handle<v8::Value> (*)(const int&)’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
In file included from /home/james/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../src/manatee.cc:1:
/home/james/.node-gyp/0.11.10/deps/v8/include/v8.h:3346:34: error:   initializing argument 1 of ‘static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)’ [-fpermissive]
make: *** [Release/obj.target/manatee/src/manatee.o] Error 1
make: Leaving directory `/home/james/projects/node-manatee/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:104:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:862:12)
gyp ERR! System Linux 3.8.0-35-generic
gyp ERR! command "node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/james/projects/node-manatee
gyp ERR! node -v v0.11.10
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
james@agape ~/projects/node-manatee $

**Comment by jamesdwilson** [comment]
Please see https://github.com/voodootikigod/node-serialport/issues/474
