### ISSUE TITLE
Start screen renders blank teal screen

### ISSUE THREAD

**Issue by jamesdwilson** [lamassu/lamassu-machine#54]
# Note: I did comment out a small block referencing raqia per #53.

None of the page elements show, but are in the DOM as evident by page inspector in chrome. 

No console errors or errors loading assets (I commented out invalid font references also).

**Comment by jamesdwilson** [comment]
If I set the element with the classes "viewport idle_state" to display:inline manually everything seems to work as expected.

**Comment by freynder** [comment]
Just confirming, I experience exactly the same issues as reported here and in #53. Also need to remove the cursor: none; statement to be able to see my mouse pointer in the mock setup.

**Comment by naconner** [comment]
Old issue so closing. Instructions for latest v3 beta here:

https://github.com/lamassu/lamassu-machine/wiki/Running-v3-locally-on-Debian-or-Ubuntu
https://support.lamassu.is/hc/en-us/articles/115001203791-Setting-up-the-Admin-Beta-
