### ISSUE TITLE
Nexus freezes in idle (0.4.13)

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-machine#58]
Despite the reintroduction of reaper.js, machine still presents occasional freezes which are not recovered from until manually reset.

**Instance A**
Pressed Start button, shown animated 'scan QR code' screen, screen unresponsive. Did not shut down upon power plug pull. Required holding of Nexus power button.

https://gist.github.com/anonymous/9e406d03e9ba8b48bb70#file-gistfile1-txt-L31

Follows a previously observed pattern in which the machine freezes within 1-2 hours after a regularly scheduled reboot, thereafter ceasing to produce hourly log entries.

**Prior examples**: https://github.com/lamassu/lamassu-machine/issues/14

**Comment by naconner** [comment]
**Instance B**
Reported to be frozen on 'scan QR code'. Was not pinging updater service during this time. Subsequent restart was manually performed:

https://gist.github.com/naconner/71916d627b0967072f13#file-gistfile1-txt-L117

**Comment by naconner** [comment]
These two instances resulted in a drained battery:

Found frozen on Hello screen, manually rebooted:
https://gist.github.com/naconner/235e8fcf96277393d9f7#file-gistfile1-txt-L441

Found on black screen, after battery had depleted. Rebooted manually, battery at 54%:
https://gist.github.com/naconner/fcd6835a56265c5bc63f#file-gistfile1-txt-L35

Both fit pattern of freezing within 1-2 hours after a regularly scheduled reboot, thereafter ceasing to produce hourly log entries. I have not been able to retrieve further stats on these while in progress (ps, ps aux, lsof).

Why would `reaper` not be catching these instances? Could we have a tool like `monit` monitor the logs for a new entry every so often, and, finding none, reboot the machine? Instead of making node.log more verbose, how about a secondary log file with more frequent entries produced by the `lamassu-machine` process?

**Comment by aawilliams** [comment]
Mine is doing this several times per week. when it does, I find it on the QR scan screen. In the example below, it happened in the middle of the transaction after pressing send. It was found on the sending screen.

https://gist.github.com/aawilliams/29dd5c626f3b655032f0

**Comment by naconner** [comment]
Hi @aawilliams. Thanks for the report. Those appear to be separate issues, for which we're testing out patches.

Freeze on scan QR screen – reaper.js: https://github.com/lamassu/lamassu-machine/commit/5233ec957b0f8ada6cf3c4dbda42468b65f14a24

Freeze on 'Sending bitcoins' – id003.js & id003rs232.js: https://github.com/lamassu/lamassu-machine/commit/6340f4a8f7cf4b33a05889c428e28e0ec5850231

**Comment by naconner** [comment]
Hangs on 'Scan QR code' screen resolved with 0.5.14.

Hangs on 'Sending bitcoins' due to bill rejection resolved with 0.5.17.

Closing.
