### ISSUE TITLE
Port to projectskyhook machines

### ISSUE THREAD

**Issue by stp-ip** [lamassu/lamassu-machine#59]
Would be nice to run stable lamassu code on old projectskyhook machines.
For orientation mismatch one could turn the projectskyhook by 180° for easier integration.

**Comment by naconner** [comment]
Hi Michael. That would be great, although there are some additional considerations:

- The Skyhook uses the built-in tablet camera. We use a separate webcam.
- The library that communicates with the bill validator would need to be written.
- The cable to our Nexus-based model is specially designed and splits both data and power when connecting to the USB hub. With the Skyhook, it communicates with the other components by tethering to a RaspberryPi. 

It'd certainly be an interesting project, though it would be a bit move involved.

**Comment by stp-ip** [comment]
As there was nothing in the issue tracker, I at least wanted to start the proposition.
All of these issues have solutions, but are quite valid points.  
A webcam could be added as an easier fix.  
Perhaps a js library already exists. The producer is: http://pyramidacceptors.com, but I couldn't look for the product yet.  
If lamassu is really running, I doubt that the tethering is still needed and a split communication is not out of the question.  
I mean even with a 50€/$ expension pack: "make your skyhook compatible with lamassu" kind of thing, would not be too bad as a compromise.  
But as I said. Throwing out ideas to get a discussion started at least.

**Comment by naconner** [comment]
We still don't have plans for this at this time, so closing this issue. Thanks again though.
