### ISSUE TITLE
Fee column in the transaction log show "0"

### ISSUE THREAD

**Issue by Transisto** [lamassu/lamassu-machine#66]
Amongst :
id session_id device_fingerprint to_address satoshis fiat currency_code **fee** incoming stage authority tx_hash error created

We're selling at 3% above bitcoinaverage.

Its very inconvenient when doing accounting to keep track of the transaction fee manually when it's being changed often.

**Comment by naconner** [comment]
@Transisto Agreed, not seeing that recorded on my instances either, although fees are recorded within the bitcoind transaction database or via BitGo's CSV export (https://www.bitgo.com/enterprise/personal/reports).

What wallet are you using?

This should probably be in lamassu-server since it deals with the postgres database.

**Comment by Transisto** [comment]
I was expecting to see the markup fee there. The bitcoin transaction fee is negligible.

I find the reporting provided by the Lamassu very poor, I need to keep track of the markup fee and do many manipulation in excel to be able to provide a profit report to the host of the ATM. I also wish there was a way to view or download it from the web UI.

**Comment by naconner** [comment]
Thanks for the clarification. I've brought this up with the team and will keep you posted.

We're at work on our next-generation admin, which will have much more insight available from within the admin.

**Comment by naconner** [comment]
Included in v3 beta:

```
                                      Table "public.cash_in_txs"
       Column       |           Type           |                      Modifiers                       
--------------------+--------------------------+------------------------------------------------------
 id                 | uuid                     | not null
 device_id          | text                     | not null
 to_address         | text                     | not null
 crypto_atoms       | bigint                   | not null
 crypto_code        | text                     | not null
 fiat               | numeric(14,5)            | not null
 fiat_code          | text                     | not null
 fee                | bigint                   | 
 tx_hash            | text                     | 
 phone              | text                     | 
 error              | text                     | 
 created            | timestamp with time zone | not null default now()
 send               | boolean                  | not null default false
 send_confirmed     | boolean                  | not null default false
 timedout           | boolean                  | not null default false
 send_time          | timestamp with time zone | 
 error_code         | text                     | 
 operator_completed | boolean                  | not null default false
 send_pending       | boolean                  | not null default false
 cash_in_fee        | numeric(14,5)            | not null
 cash_in_fee_crypto | bigint                   | not null
 minimum_tx         | integer                  | not null
 customer_id        | uuid                     | default '47ac1184-8102-11e7-9079-8f13a7117867'::uuid
 tx_version         | integer                  | not null
```

Closing.
