### ISSUE TITLE
A flat fee + % to better reflect real costs.

### ISSUE THREAD

**Issue by Transisto** [lamassu/lamassu-machine#72]
I've heard many times operators having to take off machines because of too many "unwanted" people coming in their store to buy bitcoin.

For example an ATM that has high number of transactions but low dollar volume.
If 20-30 people come a store to buy 10-20$ worth of bitcoin at 4% that doesn't make much revenue compared to how much risk and distraction these people can be. (if they do not buy additional merchandise from the ATM host.)

How hard would it be to add for example a 1$ flat cost to the % fee ? And as an operator would you use that feature ?

**Comment by Transisto** [comment]
https://github.com/lamassu/lamassu-server/blob/668ba7d08cb67b2a260f39b01018b091139b7805/lib/routes.js#L74

https://github.com/lamassu/lamassu-server/blob/668ba7d08cb67b2a260f39b01018b091139b7805/lib/plugins.js#L351

What would be the smallest change I could do to hardcode a +1$ flat fee per transaction ?

**Comment by naconner** [comment]
Hi @Transisto, those two lines would appear to support a hard-coded value. It's also possible to edit a ticker module to add a fixed value or multiplier before the commission rate is applied: https://github.com/lamassu/lamassu-bitpay/blob/master/ticker.js#L36-L38

**Comment by Transisto** [comment]
Are you sure these price modifier line add 1$ to the transaction and not to the bitcoin price ?

If someone buy for only 5$ I'd want him to receive 5 - 1 - (5*0.04) = $3.80 worth of bitcoin (at 4%) instead of $4.80

**Comment by naconner** [comment]
You're right, that would add a fixed dollar amount to the ticker price.

The issue with requiring a flat fee in addition to the commission is that the machine interface is not currently equipped to handle that. How would it alert the user to the arrangement?

Importantly, how would it handle $1 bills? It would need to either deny $1 bills as the first inserted bill, eat the $1 bills until the user covers the flat fee (only above which do they receive bitcoins), or disable accepting $1 bills entirely.

In any of these cases, if the user inserts $5 they'll observe a greater than 20% percent fee, perhaps coming away with the impression that this is the fee for all amounts (explanatory screen text is often disregarded).

**Comment by Transisto** [comment]
Our lowest denomination in Canada are the 5$ bill and we had intended on
adding a sign on the machine. 1$ per transaction.  For US people I think it
would be an awesome feature to not accept 1$ bill at all.

**Comment by naconner** [comment]
Added to v3 beta: https://support.lamassu.is/hc/en-us/articles/115001211752-Fixed-fees-minimum-transaction-amounts
