### ISSUE TITLE
Can't connect to mock server OSX

### ISSUE THREAD

**Issue by songproducer** [lamassu/lamassu-machine#74]
When executing:

LAMASSU_ENV=debug bin/lamassu-server --http

I get:

{"name":"lamassu-server","hostname":"Leos-MacBook-Pro.local","pid":12831,"level":30,"msg":"Version: 2.2.14","time":"2016-05-25T18:59:49.365Z","v":0}
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
lamassu-server is listening on local port 7070
lamassu-server listening on port 3000 (http)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete](net.js:896:19)

**Comment by naconner** [comment]
Hi @songproducer. After cloning the repository, did you run `npm install` while in the directory?

I don't have much experience running the server locally, as I use a DigitalOcean instance for the full stack.

You can manually pair a DO droplet to the local machine using this method: https://github.com/lamassu/lamassu-machine/wiki/Manually-pairing-to-lamassu-server

**Comment by songproducer** [comment]
>After cloning the repository, did you run npm install while in the directory?

Yes

I get this warning though:
>npm WARN package.json lamassu-machine@0.5.26 No license field.

**Comment by naconner** [comment]
The warning is from lamassu-machine, rather than lamassu-server. So to confirm, you ran `npm install` on both?

We can ignore messages for WARNs, though not any with ERR.

If you use VirtualBox to run Ubuntu, you can set up lamassu-machine via this method:
https://github.com/lamassu/lamassu-machine/wiki/Running-on-Ubuntu-14.04-i386

**Comment by songproducer** [comment]
>So to confirm, you ran npm install on both?
Yes

If I run the lamassu server program directly inside the bin folder I get this:
```
./lamassu-server 
{"name":"lamassu-server","hostname":"Leos-MacBook-Pro.local","pid":62563,"level":30,"msg":"Version: 2.2.14","time":"2016-05-27T19:57:59.772Z","v":0}
--key and --cert are required
```

**Comment by naconner** [comment]
Thanks. The key and certificate are generated during the lamassu-install process, so if installed on a DO droplet, these will be discovered automatically:

https://github.com/lamassu/lamassu-install#instructions

**Comment by naconner** [comment]
Old issue, closing. Instructions for latest v3 beta here:

https://github.com/lamassu/lamassu-machine/wiki/Running-v3-locally-on-Debian-or-Ubuntu
https://support.lamassu.is/hc/en-us/articles/115001203791-Setting-up-the-Admin-Beta-
