### ISSUE TITLE
Preparing a backup tablet ? (nexus 7)

### ISSUE THREAD

**Issue by Transisto** [lamassu/lamassu-machine#78]
I have a ATMs installed and I would like to get ready to replace a screen/tablet as fast as possible.

How can I prepare a tablet so that I can save time should it be vandalized ?

http://support.lamassu.is/support/solutions/articles/1000219180-re-flashing-the-nexus-tablet-with-a-generic-image

**Comment by naconner** [comment]
Hi @Transisto. The above article links to a Google Drive folder with further directions. However, if you had downloaded `sencha-image.img` prior to now, please download it again, as we've just updated the image to ping our new update server.

This will be a non-functional version that allows it to connect for updates, so let us know once flashed and we'll push the latest version.

**Comment by Transisto** [comment]
When following the instruction above I get stuck.

At step :  "fastboot oem off­-mode-­charge 0"
The tablet rebooted in normal mode.
(could be because cable might have gotten loose)

I've put it back in recovery mode then at step : "fastboot flash boot sencha.bootimg"
I get : 
sending 'boot' (2928 KB)...
FAILED (command write failed (Invalid argument))
finished. total time: 0.004s`

**Comment by naconner** [comment]
Fastboot can be particular about USB cables. I would try a different brand.

**Comment by naconner** [comment]
Further assistance can be provided by our support@lamassu.is team. Closing.
