### ISSUE TITLE
"TypeError: Cannot read property 'removeAllListeners' of undefined" when running

### ISSUE THREAD

**Issue by LuiDavinci** [lamassu/lamassu-machine#97]
So everytime I run the program to test it, in the terminal it gives me:

2018-01-29T18:35:59.018Z LOG crypto Machine software initialized. 
2018-01-29T18:35:59.045Z LOG Listening on websocket port 8080
2018-01-29T18:35:59.051Z LOG USB reset not set up.
2018-01-29T18:35:59.060Z LOG new brain state: virgin
2018-01-29T18:35:59.061Z LOG browser not connected
2018-01-29T18:35:59.064Z LOG server bound
2018-01-29T18:35:59.068Z LOG version: 3.5.0, cpuLoad: 0.02, memUse: 51.4 MB, memFree: 18.3%
  nodeUptime: 0.00h, osUptime: 2.29h

after that it does nothing, and the browser on localhost:8080 it simply says "upgrade required" and start.html just remains empty in its background color.

How exactly do I fix this?

**Comment by LuiDavinci** [comment]
So I found the problem with just the background color, in the HTML the App.js was referenced in a different location, i fixed that so that I could "kinda" interact with the machine. A different problem now occures when I try to click on test, it says "TypeError: Cannot read property 'removeAllListeners' of undefined"
however on localhost:8080 it still displays upgrade required.

**Comment by naconner** [comment]
Our instructions for running the machine locally can be found here: https://github.com/lamassu/lamassu-machine/wiki/Running-v3-locally-on-Debian-or-Ubuntu

Those issues shouldn't present if performing the steps above.

**Comment by LuiDavinci** [comment]
@naconner  Thanks for the Info, I am almost through but confused by that statement:

[In the admin window, click add machine, give it a name, and when you're presented with the QR code, open Chromium/Chrome's developer tools and locate the portion following the word TOTEM.]

What admin window?
